fixtures:
  repositories:
    'redis': 'git://github.com/fsalum/puppet-redis.git'
    'nginx': 'git://github.com/jfryman/puppet-nginx.git'
    'git': 'git://github.com/puppetlabs/puppetlabs-git.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'apt': 'git://github.com/puppetlabs/puppetlabs-apt.git'
    'logrotate': 'git://github.com/evenup/evenup-logrotate.git'
  symlinks:
    "gitlab_requirements": "#{source_dir}"
