name    'puppet-gitlab-requirements'
version '0.0.1'
source  'https://github.com/sbadia/puppet-gitlab-requirements'
author  'Sebastien Badia'
license 'GPLv3'
summary 'Puppet GitLab Requirments Module'
description 'Module to install requirements for GitLab using puppet'
project_page 'https://github.com/sbadia/puppet-gitlab-requirements/'
dependency 'fsalum/redis', '>= 0.0.5'
dependency 'puppetlabs/ruby', '>= 0.0.2'
dependency 'puppetlabs/git', '>= 0.0.2'
dependency 'saz/ssh', '>= 1.2.0'
