name    'sbadia-gitlab_requirements'
version '0.0.2'
source  'https://github.com/sbadia/puppet-gitlab-requirements'
author  'Andrew Tomaka, Sebastien Badia'
license 'GPLv3'
summary 'Puppet GitLab Requirments Module'
description 'Module to install requirements for GitLab using puppet'
project_page 'https://github.com/sbadia/puppet-gitlab-requirements/'
dependency 'fsalum/redis', '>= 0.0.5'
dependency 'jfryman/nginx', '>= 0.0.2'
dependency 'puppetlabs/git', '>= 0.0.2'
dependency 'puppetlabs/mysql', '>= 0.6.1'
dependency 'puppetlabs/ruby', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
dependency 'evenup/logrotate', '>= 1.0.3'
